### ISSUE TITLE
Genre years are estimated visually

### ISSUE THREAD

**Issue by igorbrigadir** [igorbrigadir/ishkurs-guide-dataset#4]
Currently it's a rough decade, based on where the node is visually, some are closer to borders than others, and i've arbitrarily placed them in what i thought they should be in if they were on the edge. They can be more precisely defined based on the release years of the tracks in that genre instead.

**Comment by Apelli** [comment]
Hi. Sorry for the comment, it probably doesn't here, but I am trying to run the 2.5 guide since is no longer available on the Techno.org page and neither can be accessed with archive.net (at least for me). So I found this site and your repository, and I am trying to run(visualize the content but I am honestly lost since I don't know anything about coding/programming, so I wanted to ask, how do I make to run the 2.5 guide? can I run it on the browser or do I have to download it? if so, how I play it once is downloaded, because I don't see any exe file?.
Sorry for the comment, but hopefully you can help me at trying to navigate and experience the 2.5 guide once again.

**Comment by igorbrigadir** [comment]
Ah! Seems like you got it to work with this approach via Twitter: https://twitter.com/IgorBrigadir/status/1477491983971237890?s=20

Gonna close this too, because I don't think I'll end up changing any of the data now. It's "good enough". Sad to hear techno.org is down though.
